###
GET http://localhost:3000/checker

###
POST http://localhost:3000/checker
Content-Type: application/json

{
  "name":"테스트 사이트",
  "url": "https://naver.com1",
  "allowStatus": [200],
  "disallowStatus": ["*"],
  "chanel":["slack"],
  "isReset": false
}
